# The name of the container in the pod template must be kibana
# add a custom setting for kibana
{{- if .Values.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-cluster
  namespace: {{ .Values.namespace }}
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: {{ .Values.clusterName | quote }}
    namespace: {{ .Values.namespace }}
  {{- if .Values.kibana.http }}
  http:
{{ toYaml .Values.kibana.http | indent 4 }}
  {{- end }}
  {{- if .Values.kibana.podTemplate }}
  podTemplate:
{{ toYaml .Values.kibana.podTemplate | indent 4 }}
  {{- end }} 


{{- end }}
